name: CI

on: 
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: pdm-project/setup-pdm@v3
      - name: Install Dependencies
        run: pdm sync
      - name: Build & publish
        run: pdm publish -u __token__ -p ${{ secrets.PYPI_TOKEN }}
